"""tablica povezivanja

Revision ID: 0070d463075e
Revises: f9151fbac0b7
Create Date: 2019-05-06 14:24:59.421091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0070d463075e'
down_revision = 'f9151fbac0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablica_povezivanja',
    sa.Column('izlet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['izlet_id'], ['izlet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('relacija_sudionik_izlet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relacija_sudionik_izlet',
    sa.Column('izlet_id', sa.INTEGER(), nullable=True),
    sa.Column('sudionik_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['izlet_id'], ['izlet.id'], ),
    sa.ForeignKeyConstraint(['sudionik_id'], ['user.id'], )
    )
    op.drop_table('tablica_povezivanja')
    # ### end Alembic commands ###
