"""profile pictures2

Revision ID: 4d9337f411bc
Revises: b0966108f37a
Create Date: 2019-05-07 22:19:39.565581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9337f411bc'
down_revision = 'b0966108f37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profilepicture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profilepictures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profilepictures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profilepicture')
    # ### end Alembic commands ###
