"""izlet column picture update

Revision ID: ab690c0322e7
Revises: ad6b6a33a0dc
Create Date: 2019-05-09 10:45:29.095541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab690c0322e7'
down_revision = 'ad6b6a33a0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('izlet', sa.Column('slika_izleta', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('izlet', 'slika_izleta')
    # ### end Alembic commands ###
