"""dodana profilna

Revision ID: ad6b6a33a0dc
Revises: 4d9337f411bc
Create Date: 2019-05-08 09:07:05.590134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6b6a33a0dc'
down_revision = '4d9337f411bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profilepicture')
    op.add_column('user', sa.Column('profilna_slika', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilna_slika')
    op.create_table('profilepicture',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
