"""sudionici

Revision ID: f9151fbac0b7
Revises: a75a15d2d2a1
Create Date: 2019-05-06 13:43:07.647760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9151fbac0b7'
down_revision = 'a75a15d2d2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('izlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=True),
    sa.Column('cijena', sa.Float(), nullable=True),
    sa.Column('lokacija', sa.String(length=100), nullable=True),
    sa.Column('datum_polaska', sa.DateTime(), nullable=True),
    sa.Column('datum_povratka', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('opis', sa.String(length=500), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_izlet_naziv'), 'izlet', ['naziv'], unique=False)
    op.create_index(op.f('ix_izlet_timestamp'), 'izlet', ['timestamp'], unique=False)
    op.create_table('relacija_sudionik_izlet',
    sa.Column('izlet_id', sa.Integer(), nullable=True),
    sa.Column('sudionik_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['izlet_id'], ['izlet.id'], ),
    sa.ForeignKeyConstraint(['sudionik_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacija_sudionik_izlet')
    op.drop_index(op.f('ix_izlet_timestamp'), table_name='izlet')
    op.drop_index(op.f('ix_izlet_naziv'), table_name='izlet')
    op.drop_table('izlet')
    # ### end Alembic commands ###
